/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANCO_H_RPCGEN
#define _BANCO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct record {
	int id;
	double value;
};
typedef struct record record;

#define BANPROG 0x20000003
#define BANCOVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CRIA_CONTA 1
extern  int * cria_conta_1(void *, CLIENT *);
extern  int * cria_conta_1_svc(void *, struct svc_req *);
#define EXCLUI_CONTA 2
extern  int * exclui_conta_1(int *, CLIENT *);
extern  int * exclui_conta_1_svc(int *, struct svc_req *);
#define SAQUE 3
extern  double * saque_1(record *, CLIENT *);
extern  double * saque_1_svc(record *, struct svc_req *);
#define DEPOSITO 4
extern  double * deposito_1(record *, CLIENT *);
extern  double * deposito_1_svc(record *, struct svc_req *);
#define CONSULTA_CONTA 5
extern  double * consulta_conta_1(int *, CLIENT *);
extern  double * consulta_conta_1_svc(int *, struct svc_req *);
extern int banprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CRIA_CONTA 1
extern  int * cria_conta_1();
extern  int * cria_conta_1_svc();
#define EXCLUI_CONTA 2
extern  int * exclui_conta_1();
extern  int * exclui_conta_1_svc();
#define SAQUE 3
extern  double * saque_1();
extern  double * saque_1_svc();
#define DEPOSITO 4
extern  double * deposito_1();
extern  double * deposito_1_svc();
#define CONSULTA_CONTA 5
extern  double * consulta_conta_1();
extern  double * consulta_conta_1_svc();
extern int banprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_record (XDR *, record*);

#else /* K&R C */
extern bool_t xdr_record ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BANCO_H_RPCGEN */
