/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "banco.h"

bool_t
xdr_record (XDR *xdrs, record *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}
